{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.configmap.annotations | nindent 8 }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
{{- end }}