{{- if .Values.configmaps }}
{{- range .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "helm.selectorLabels" . | nindent 8 }}
  annotations:
    {{- toYaml .annotations | nindent 8 }}
data:
  {{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}