{{- if .Values.configmaps }}
{{- range .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
  annotations:
    {{- toYaml .annotations | nindent 8 }}
    {{- toYaml .annotations | nindent 8 }}
      {{- with .Values.deploymentAnnotations }}
    {{- toYaml . | nindent 8 }}
data:
  {{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}