{{- if .Values.secrets }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
  annotations:
    {{- toYaml .annotations | nindent 8 }}
    {{- include "helm.annotations" . | nindent 4 }}
type: {{ .type }}
data:
  {{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}