{{- if .Values.secrets }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
  annotations:
    {{- toYaml .annotations | nindent 8 }}
    {{- with .Values.deploymentAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
type: {{ .type }}
data:
  {{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}