{{- if .Values.secrets }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  annotations:
    {{- toYaml .annotations | nindent 8 }}
type: {{ .type }}
data:
  {{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}